version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "3.10"
    jobs:
        pre_install:
            - pip install uv
        install:
            - uv pip install .[docs]

sphinx:
    configuration: docs/source/conf.py

formats: all
