name: Build and Push Docs as PDF

on:
  push:
    tags:
      - "v*"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Sphinx and Requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended texlive-xetex
          pip install sphinx
          pip install -r requirements-docs.txt

      - name: Build PDF Documentation
        run: |
          cd docs
          sphinx-build -b latex source _build/latex
          cd _build/latex
          latexmk -pdf -quiet *.tex
          mkdir -p ../../release
          cp *.pdf ../../release/manual.pdf

      - name: Create GitHub Release and Upload PDF
        uses: softprops/action-gh-release@v2
        with:
          files: docs/release/manual.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
