name: Publish Python 🐍 package

on:
  push:
    tags:
      - "v*.*.*" # Example: v1.2.3 will trigger this

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip-existing: true

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' && github.repository == 'osama-ata/PyP6Xer-dev'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
