name: Publish Python package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write   # For Trusted Publishing
  contents: write   # For GitHub Release

jobs:
  publish:
    runs-on: ubuntu-latest
    if: success()  # Only publish if all previous jobs (test.yml) succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv pip install --system -r requirements.txt

      - name: Set version from Git tag
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          echo "Detected tag version: $TAG_VERSION"
          sed -i "s/^version = .*/version = \"$TAG_VERSION\"/" pyproject.toml

      - name: Build package
        run: uv build --no-sources

      - name: Publish to PyPI
        run: uv publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
