name: Publish

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install uv
              run: pip install uv

            - name: Create venv
              run: uv venv

            - name: Install build tool
              run: uv pip install build

            - name: Build package
              run: uv venv -- python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
