name: Test

on:
    push:
        branches: [main, master]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install uv
              run: pip install uv

            - name: Create venv
              run: uv venv

            - name: Install dependencies
              run: uv pip install .[test]

            - name: Run tests
              run: .venv/bin/python -m pytest
